version: "3"
services:  

  proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  redis:
    image: redis
    ports:
      - 6379:6379

  socket:
    build:
      context: ./microservices/SocketIOService
      dockerfile: Dockerfile
    expose:
      - 3000
    depends_on:
      - redis

  updateDeviceService:
    build:
      context: ./microservices/UpdateDeviceService
      dockerfile: Dockerfile
    expose:
        - "80"