version: "3"
services:
        
  proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - update
      - socket
  
  redis:
    image: redis
    ports:
      - 6379:6379

  watchtower:
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    #restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  socket:
    image: swierzewskibartosz/micro.socket_io_service
    expose:
      - 3000    
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - redis
      - watchtower

  update:
    image: swierzewskibartosz/updatedeviceservice
    expose:
      - 80  
    volumes:
      - ./databases:/update.db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower