version: "3"
services:
        
  proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - update
      - socket
      - auth
      - app
  
  redis:
    image: redis
    ports:
      - 6379:6379

  watchtower:
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    #restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120

  socket:
    image: swierzewskibartosz/socketioservice
    expose:
      - 3000    
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - redis
      - watchtower

  update:
    image: swierzewskibartosz/updatedeviceservice
    expose:
      - 80        
    # Do usunięcia po testach
    volumes:
      - ./databases/update.db:/update.db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower

  auth:
    image: swierzewskibartosz/authenticationservice
    expose:
      - 80  
    # Do usunięcia po testach
    volumes:
      - ./databases/auth.db:/auth.db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower
      
  app:
    image: swierzewskibartosz/deviceservice
    expose:
      - 80  
    # Do usunięcia po testach
    volumes:
      - ./databases/device.db:/device.db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower