version: "3"
services:
        
  proxy:
    container_name: proxy
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - update
      - socket
      - auth
      - device
      - app
  
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  watchtower:
    container_name: watchtower
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    #restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120

  socket:
    container_name: socket
    image: swierzewskibartosz/service_socket_io
    expose:
      - 3000    
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - redis
      - watchtower

  update:
    container_name: update
    image: swierzewskibartosz/service_update_device
    expose:
      - 80        
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower

  auth:
    container_name: auth
    image: swierzewskibartosz/service_authentication
    expose:
      - 80  
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower
      
  device:
    container_name: device
    image: swierzewskibartosz/service_device
    expose:
      - 80  
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower

  app:
    container_name: app
    image: swierzewskibartosz/angular_spa
    expose:
      - 80  
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower